language: php
php:
  - '5.4'
  - '5.5'
  - '5.6'
  - '7.0'
  - '7.1'
  - hhvm

before_script:
  - composer install --prefer-dist --dev

script:
  - ./vendor/bin/phpunit --bootstrap ./vendor/autoload.php ./Tests/EncrytionTest.php

matrix:
  fast_finish: true
